### ISSUE TITLE
REQUEST: New Approver/Reviewers abilities added for spinnaker-monitoring repo

### ISSUE THREAD

**Issue by kevinawoo** [spinnaker/governance#116]
Hi, I noticed that https://github.com/spinnaker/spinnaker-monitoring is not in the list of repos that approvers/reviewers have access to. Also mergify is also not setup in this repo.

I vote for adding this into the normal Spinnaker approvers/reviewers workflow also.

**Comment by ezimanyi** [comment]
I can do this; I think was just an oversight rather than something we explicitly excluded.

**Comment by ezimanyi** [comment]
This is done; `oss-reviewers` and `oss-approvers` now have the same permissions on `spinnaker-monitoring` as on the other repos, and it has been set up with mergify.
