### ISSUE TITLE
REQUEST: New Reviewer status for lorin

### ISSUE THREAD

**Issue by lorin** [spinnaker/governance#117]
### Github Username

lorin

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @luispollo 
- @emjburns 

### List of qualifications for this position

Organizations with a stake in Spinnaker: Netflix

- Links to public Spinnaker PRs

Author:

1. [feat(repository): disallow duplicate artifact refs](https://github.com/spinnaker/keel/pull/841)
1. [fix(veto): fix Value annotation syntax](https://github.com/spinnaker/keel/pull/895)
1. [feat(api): test endpoint that throws an exception](https://github.com/spinnaker/keel/pull/919)
1. [fix(metrics): record drift from last resource check](https://github.com/spinnaker/keel/pull/976)
1. [fix(actuator): add coroutine id to help debug](https://github.com/spinnaker/keel/pull/985)
1. [fix(resource): tweak thread model, add more debug logging](https://github.com/spinnaker/keel/pull/1001)

Reviewer:

1. [Don't keep re-trying the same bake](https://github.com/spinnaker/keel/pull/997)
1. [fix(artifacts): don't keep marking as deployed over and over](https://github.com/spinnaker/keel/pull/982)
1. [feat(artifact): introduce SKIPPED status, more data for previous](https://github.com/spinnaker/keel/pull/959)
1. [fix(artifact): more resilient app version parsing](https://github.com/spinnaker/keel/pull/948)
1. [fix(events): Fix paused events for resources due to pausing application](https://github.com/spinnaker/keel/pull/842)

**Comment by ajordens** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1!

**Comment by robzienert** [comment]
TOC +1

**Comment by ezimanyi** [comment]
PR has been merged and @lorin has been added to `oss-reviewers`.
