### ISSUE TITLE
REQUEST: New Approver status for danielpeach

### ISSUE THREAD

**Issue by danielpeach** [spinnaker/governance#118]
### Github Username

@danielpeach

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

@maggieneterval 
@ezimanyi 
@claymccoy 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Armory
- Links to public Spinnaker PRs

https://github.com/spinnaker/orca/pull/2346
https://github.com/spinnaker/orca/pull/2257
https://github.com/spinnaker/deck/pull/5617
https://github.com/spinnaker/clouddriver/pull/743
https://github.com/spinnaker/orca/pull/2217

**Comment by ezimanyi** [comment]
TOC +1

**Comment by maggieneterval** [comment]
Regular person +1

**Comment by plumpy** [comment]
TOC (and also regular person) +1

[![Mase "Welcome Back" video](https://img.youtube.com/vi/rIvEiTrq9kk/0.jpg)](https://www.youtube.com/watch?v=rIvEiTrq9kk)

**Comment by robzienert** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1
