### ISSUE TITLE
REQUEST: New Approver status for allisaurus

### ISSUE THREAD

**Issue by allisaurus** [spinnaker/governance#120]
### Github Username

@allisaurus 

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @clareliguori 
- @robzienert 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: AWS
- Links to public Spinnaker PRs

Select reviews
* https://github.com/spinnaker/clouddriver/pull/4496
* https://github.com/spinnaker/deck/pull/7837
* https://github.com/spinnaker/clouddriver/pull/4218
* https://github.com/spinnaker/clouddriver/pull/4409
* https://github.com/spinnaker/clouddriver/pull/4411
* https://github.com/spinnaker/deck/pull/7949
* https://github.com/spinnaker/clouddriver/pull/4340
* https://github.com/spinnaker/spinnaker.github.io/pull/1736

Commits
* https://github.com/spinnaker/clouddriver/commits?author=allisaurus
* https://github.com/spinnaker/deck/commits?author=allisaurus
* https://github.com/spinnaker/orca/commits?author=allisaurus
* https://github.com/spinnaker/kork/commits?author=allisaurus
* https://github.com/spinnaker/spinnaker.github.io/commits?author=allisaurus

**Comment by ezimanyi** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1

**Comment by plumpy** [comment]
Added you to `oss-approvers`, let me know if you have any issues!
