### ISSUE TITLE
REQUEST: New Approver status for lorin

### ISSUE THREAD

**Issue by lorin** [spinnaker/governance#121]
### Github Username

@lorin 

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @luispollo 
- @emjburns 

### List of qualifications for this position

- Name of organization with significant stake in project: Netflix
- Links to public Spinnaker PRs

Select reviews

* https://github.com/spinnaker/keel/pull/1055
* https://github.com/spinnaker/keel/pull/1023
* https://github.com/spinnaker/keel/pull/997
* https://github.com/spinnaker/keel/pull/959
* https://github.com/spinnaker/keel/pull/957
* https://github.com/spinnaker/keel/pull/905

Commits

* https://github.com/spinnaker/keel/commits?author=lorin
* https://github.com/spinnaker/spinnaker.github.io/commits?author=lorin

**Comment by ezimanyi** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by ajordens** [comment]
Majority approved, welcome @lorin.
