### ISSUE TITLE
ACTION NEEDED: SIG for Tencent Cloud Provider

### ISSUE THREAD

**Issue by robzienert** [spinnaker/governance#128]
@shengyu @donghun221

The Tencent cloud provider has been identified as not having a Special Interest Group created for it. A SIG must be formed for each Cloud Provider to offer the community a communications channel for feedback and support. Since there is not already a SIG formed for this cloud provider, one will need to be created.

With the creation of the SIG, adherence to the [Cloud Provider Requirements](https://github.com/spinnaker/governance/blob/master/cloud-provider-requirements.md) will be required. 

**If no action is taken on this issue by the 1st of June, 2020, this cloud provider will be a candidate for removal from the core Spinnaker project and may be moved to a plugin where it will need to be maintained separately.**

## Why was I assigned this issue?

We were unable to find a complete list of email address contacts for this cloud provider to contact the owners directly. Please copy any individuals that may be a better contact for fielding this issue if needed.

## What we need from you

A new SIG needs to be formed for this cloud provider. You can read about the process on forming a SIG following the directions on the [SIG Lifecycle](https://github.com/spinnaker/governance/blob/master/sig-lifecycle.md) page. 

If continued support of this cloud provider is not planned by your organization, please let us know so we may plan accordingly.

**Comment by shengyu** [comment]
OK, I will submit the SIG proposal this week.

**Comment by robzienert** [comment]
@shengyu Ping - it's been a month since your last update, but we haven't seen a SIG proposal. Is this still planned?
