### ISSUE TITLE
REQUEST: New Approver status for german-muzquiz

### ISSUE THREAD

**Issue by german-muzquiz** [spinnaker/governance#130]
### Github Username

@german-muzquiz

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @ethanfrogers 
- @kevinawoo 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Armory
- Links to public Spinnaker PRs

https://github.com/spinnaker/halyard/pull/1644
https://github.com/spinnaker/kork/pull/380
https://github.com/spinnaker/halyard/pull/1416
https://github.com/spinnaker/clouddriver/pull/3716
https://github.com/spinnaker/deck/pull/6937

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by plumpy** [comment]
Moved you from oss-reviewers to oss-approvers. Welcome!
