### ISSUE TITLE
REQUEST: New Reviewer status for pkandasamy91

### ISSUE THREAD

**Issue by pkandasamy91** [spinnaker/governance#132]
### Github Username

@pkandasamy91

### Requirements

- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Sponsored by 2 Approvers

### Sponsors

- @allisaurus 
- @clareliguori 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: AWS
- Links to public Spinnaker PRs

Merged:
- https://github.com/spinnaker/deck/pull/7692
- https://github.com/spinnaker/deck/pull/7837
- https://github.com/spinnaker/deck/pull/7949
- https://github.com/spinnaker/deck/pull/8188
- https://github.com/spinnaker/clouddriver/pull/4218
- https://github.com/spinnaker/clouddriver/pull/4349
- https://github.com/spinnaker/clouddriver/pull/4496

Reviewed:
- https://github.com/spinnaker/clouddriver/pull/4526
- https://github.com/spinnaker/clouddriver/pull/4275
- https://github.com/spinnaker/clouddriver/pull/4340
- https://github.com/spinnaker/deck/pull/8186
- https://github.com/spinnaker/deck/pull/8049

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by plumpy** [comment]
Added you to the oss-reviewers and Amazon teams. Welcome!

**Comment by pkandasamy91** [comment]
Thanks @plumpy!
