### ISSUE TITLE
REQUEST: New Reviewer status for vigneshm

### ISSUE THREAD

**Issue by vigneshm** [spinnaker/governance#140]
### Github Username

@vigneshm

### Requirements

- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Sponsored by 2 Approvers

### Sponsors

- @christopherthielen 
- @erikmunson 

### List of qualifications for this position

- [Show deploying state in environments view](https://github.com/spinnaker/deck/pull/8123)
- [Add StatusBubble to denote resource status](https://github.com/spinnaker/deck/pull/8214)
- [Move details field to core and use that in titus](https://github.com/spinnaker/deck/pull/8097)
- [Update eslint plugin to include react hooks](https://github.com/spinnaker/deck/pull/7982)
- [Make server group's details field overridable](https://github.com/spinnaker/deck/pull/8029)

**Comment by ajordens** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by plumpy** [comment]
Added you to oss-reviewers, welcome!
