### ISSUE TITLE
REQUEST: New Reviewer status for zachsmith1

### ISSUE THREAD

**Issue by zachsmith1** [spinnaker/governance#147]
### Github Username

@zachsmith1

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @ethanfrogers 
- @ezimanyi 

### List of qualifications for this position

Name of organization(s) with significant stake in project: Armory, CloudFoundry
Head of CloudFoundry SIG

- Links to public Spinnaker PRs

https://github.com/spinnaker/clouddriver/pull/4544
https://github.com/spinnaker/clouddriver/pull/4600
https://github.com/spinnaker/clouddriver/pull/4611
https://github.com/spinnaker/clouddriver/pull/4624
https://github.com/spinnaker/clouddriver/pull/4653
https://github.com/spinnaker/clouddriver/pull/4667
https://github.com/spinnaker/clouddriver/pull/4678

**Comment by ezimanyi** [comment]
+1, both as TOC member and as sponsor

**Comment by plumpy** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1 as well!

**Comment by ajordens** [comment]
TOC +1
