### ISSUE TITLE
REQUEST: New Approver status for aimeeu

### ISSUE THREAD

**Issue by aimeeu** [spinnaker/governance#148]
### Github Username
@aimeeu

**This request is for `spinnaker.github.io` and `spinnaker.io` only.**

### Requirements

- [ ] Belongs to an organization with significant stake in project
- [ ] Known active participant in the community
- [ ] Has submitted at least 5 PRs of significant scope that are merged
- [ ] Is already fulfilling the Reviewer role
- [ ] Has reviewed 5 PRs of significant scope
- [ ] Sponsored by 2 Approvers

### Sponsors

- @brian-armory 
- @dorbin 

### List of qualifications for this position

- I am a tech writer at Armory, where I create and review/approve/merge content
- Active participant in the Spinnaker Documentation SIG;  overseeing the spinnaker.io migration to Hugo along with Brian Le and Ros Benoit
- `spinnaker.github.io`: 11 merged [PRs](https://github.com/spinnaker/spinnaker.github.io/pulls?q=is%3Apr+author%3Aaimeeu)
- `governance`: co-authored the [RFC](https://github.com/spinnaker/governance/pull/110) for the spinnaker.io revamp
- Previous open source experience:  worked for the CNCF on K8s docs from 8-11/2019 (merged PRs: 20 docs, 2 community, 1 sig-release, 2 reference-docs); Docs Lead for Acumos 2/2018-3/2019;  contributed docs to 3 projects in OPNFV; contributed docs content to OpenStack Congress

The Documentation SIG is severely understaffed. I discussed my moving into an Approver role a while ago with Dave Dorbin. Being an Approver will enable me to triage issues, assign folks, follow up on stale PRs, and approve/merge PRs when Dave and Brian are not available.

**Comment by plumpy** [comment]
We have a special `docs-approvers` team for this... +1 to adding you to that. Thanks!

**Comment by ezimanyi** [comment]
TOC +1 for `docs-approvers`

**Comment by ethanfrogers** [comment]
TOC +1!

**Comment by plumpy** [comment]
Sent an invite to join the org and `docs-approvers`!
