### ISSUE TITLE
REQUEST: New Approver status for @vigneshm

### ISSUE THREAD

**Issue by vigneshm** [spinnaker/governance#149]
### Github Username

@vigneshm

### Requirements

- [X] Belongs to an organization with significant stake in project
- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Is already fulfilling the Reviewer role
- [X] Has reviewed 5 PRs of significant scope
- [X] Sponsored by 2 Approvers

### Sponsors

- @christopherthielen 
- @caseyhebebrand 

### List of qualifications for this position

- Organization with significant stake in project: Netflix

Author:
- [Add capability to update the entire application configuration blob](https://github.com/spinnaker/front50/pull/817)
- [Add StatusBubble to denote resource status](https://github.com/spinnaker/deck/pull/8214)
- [Show deploying state in environments view](https://github.com/spinnaker/deck/pull/8123/files)
- [Update eslint plugin to include react hooks rules](https://github.com/spinnaker/deck/pull/7981)
- [ServerGroup details field related sharding work](https://github.com/spinnaker/deck/pull/8097)

Reviewer:
- [support for marking a version 'bad', add illustrations](https://github.com/spinnaker/deck/pull/8337)
- [Memoize defaultResult in useData.hook.ts](https://github.com/spinnaker/deck/pull/8289)
- [Add a formik hook to save/restore data](https://github.com/spinnaker/deck/pull/8249)
- [Add Launch Template data mocks](https://github.com/spinnaker/deck/pull/8252)
- [mitigate layout jank on ObjectRow + EnvironmentRow](https://github.com/spinnaker/deck/pull/8246)

**Comment by ajordens** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1
