### ISSUE TITLE
REQUEST: Nomination of Isaac Mosquera for the Steering Committee

### ISSUE THREAD

**Issue by aglover** [spinnaker/governance#151]
I nominate Isaac Mosquera to replace Erin Kidwell on the Steering Committee. 

Isaac Mosquera is CTO & Co-Founder of Armory. He has been leading an engineering and product team engaged in the Spinnaker community for three years. Prior to this, he spent 20 years architecting large-scale systems at companies such as ShareThis, Socialize and XM Satellite Radio, as well as creating high scalability/load websites for brands such as Games Radar by Future Publishing. He co-founded Armory to help enterprises innovate through happy & productive engineering teams.

Steering Committee members, please indicate your vote via a +1 for yes or a -1 for no or 0 for abstaining.

**Comment by duftler** [comment]
+1

Looking forward to having Isaac join the Steering Committee.

**Comment by pstout** [comment]
+1

**Comment by demobox** [comment]
+1
