### ISSUE TITLE
CDF TOC chair

### ISSUE THREAD

**Issue by aglover** [spinnaker/governance#163]
I nominate Isaac Mosquera to replace me on the Technical Oversight Committee for the CDF.

Isaac Mosquera is CTO & Co-Founder of Armory. He has recently joined Spinnaker steering committee and has been leading an engineering and product team engaged in the Spinnaker community for almost 4 years. Prior to this, he spent 20 years architecting large-scale systems at companies such as ShareThis, Socialize and XM Satellite Radio, as well as creating high scalability/load websites for brands such as Games Radar by Future Publishing. He co-founded Armory to help enterprises innovate through happy & productive engineering teams.

Steering Committee members, please indicate your vote via a +1 for yes or a -1 for no or 0 for abstaining.

**Comment by duftler** [comment]
+1

**Comment by pstout** [comment]
+1

**Comment by imosquera** [comment]
+1

**Comment by aglover** [comment]
+1 - I think Isaac will bring a fresh new perspective to the CDF TOC and I look forward to his contributions!

**Comment by demobox** [comment]
+1 - looking forward to your ideas for Spinnaker's future CDF TOC engagement, Isaac!

**Comment by tequilarista** [comment]
+1

**Comment by robzienert** [comment]
@aglover Looks like this has been completed?

**Comment by ajordens** [comment]
https://github.com/cdfoundation/toc/pull/83/files has been updated to reflect this.
