### ISSUE TITLE
PROPOSAL: New Cloud Provider for Yandex.Cloud

### ISSUE THREAD

**Issue by vasiliy-briginets** [spinnaker/governance#166]
### Cloud Provider

Name of cloud provider is Yandex

### Maintaining Organization(s)

Yandex.Cloud LLC

#### Point of Contact(s)

@vasiliy-briginets @g-s-v @intr13

### Requirements

- [x] Cloud Provider will be actively backed by a development team from Maintainers with a significant stake in the project.
- [x] Maintainers commit to triaging and addressing major bugs and issues with the integration in a timely manner.
- [x] Maintainers commit to handling routine maintainence tasks for the integrations, such as:
  - [x] Keeping it compatible with updates to the cloud provider itself.
  - [x] Making any cloud provider-specific changes in response to global architecture changes within Spinnaker.
- [x] Maintainers acknowledge failure to maintain cloud provider integration may prompt removal of integration from Spinnaker.
- [x] Maintainers agree to setup and maintain a Special Interest Group for the Cloud Provider integration.

**Comment by ezimanyi** [comment]
TOC +1
Please also create the proposal for the new SIG as a pull request against this repo.  You can see examples of other SIGs in the `sig-*` directories at the root of this repo.

**Comment by robzienert** [comment]
TOC +1

**Comment by vasiliy-briginets** [comment]
> TOC +1
> Please also create the proposal for the new SIG as a pull request against this repo. You can see examples of other SIGs in the `sig-*` directories at the root of this repo.

Hi, Eric! So, I did this, what is the next step?

**Comment by ezimanyi** [comment]
> Hi, Eric! So, I did this, what is the next step?

We just need to wait for a majority of the TOC to sign off on this proposal, then you can move forward with holding meetings of the SIG and making the code changes to add the provider.  We'll still waiting on @ajordens @plumpy @ethanfrogers

**Comment by plumpy** [comment]
TOC +1

**Comment by vasiliy-briginets** [comment]
> TOC +1

Hello! So, it's 3/5 now. What's next?

**Comment by vasiliy-briginets** [comment]
ping
@ezimanyi @ajordens @plumpy @ethanfrogers

**Comment by ezimanyi** [comment]
Majority of TOC has approved; closing as approved.

**Comment by vasiliy-briginets** [comment]
thank you all!
