### ISSUE TITLE
Plugin Transfer: Account Registration Plugin

### ISSUE THREAD

**Issue by nimakaviani** [spinnaker/governance#187]
### Plugin Information

The accounts registration plugin implements the [Spinnaker Account Management RFC](https://github.com/spinnaker/governance/blob/master/rfc/account-management.md) to allow Spinnaker accounts to be added dynamically from an external source (wired over HTTP) without having to restart Clouddriver. The plugin serves as a first implementation of the RFC and can be used both to load external accounts into Clouddriver and also as an example for others interested in interfacing with the Clouddriver and supplying account data dynamically. While the implementation can technically be modified to accommodate any type of account, the current implementation only supports EC2, ECS, and Lambda accounts.

The current plugin lives here: [awslabs/aws-account-registration-plugin-spinnaker](https://github.com/awslabs/aws-account-registration-plugin-spinnaker)

### Acknowledgements

- [x] Source code will be available publicly on [`spinnaker-plugins`](https://github.com/spinnaker-plugins)
- [x] Donated code must explicitly declare a license
- [x] All authors listed below will be given `maintain` permissions to the plugin repository
- [x] Plugin authors are expected to continue as primary maintainers of plugin
- [x] Spinnaker core contributors are not expected to help maintain the plugin
- [x] Spinnaker core contributors will not automatically inherit permissions for plugin repository, with the exception of the Technical Oversight Committee for administrative purposes

### Maintainers

@dkirillov @ncknt @nimakaviani

**Comment by robzienert** [comment]
See that a couple of the acknowledgements haven't been checked. Are there any hesitations on the last couple?

**Comment by plumpy** [comment]
I think I accidentally unchecked some because apparently anyone with edit access can alter them just by clicking...

**Comment by nimakaviani** [comment]
all good. I put them back in. I am working internally on the transfer will ping you two @robzienert and @plumpy when we are ready for the handoff. thank you!

**Comment by ajordens** [comment]
The repository was transferred yesterday, I believe we're in good shape now. Thanks for being the guinea pigs!
