### ISSUE TITLE
REQUEST: New Reviewer status for @dogonthehorizon <Fernando Freire>

### ISSUE THREAD

**Issue by dogonthehorizon** [spinnaker/governance#191]
### Github Username

@dogonthehorizon

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @german-muzquiz 
- @link108

### List of qualifications for this position

- https://github.com/spinnaker/kork/pull/503
- https://github.com/spinnaker/orca/pull/3966
- https://github.com/spinnaker/deck/pull/8424
- https://github.com/spinnaker/deck/pull/8652
- https://github.com/spinnaker/echo/pull/770
- https://github.com/spinnaker/front50/pull/981

I've also hosted a workshop at Spinnaker Gardening Days to encourage new contributors to the project:
https://youtu.be/Sb5CO6RQx_Q

**Comment by kevinawoo** [comment]
I'll back him 4ever! Fernando has done some great work and I'm excited to see him take on more responsibility with the community, like the role of release manager he's currently doing!

**Comment by ezimanyi** [comment]
TOC +1

**Comment by link108** [comment]
+1 🎉

**Comment by plumpy** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1
