### ISSUE TITLE
Plugin Transfer: Lambda Plugin

### ISSUE THREAD

**Issue by nimakaviani** [spinnaker/governance#192]
### Plugin Information

This plugin provides support for AWS Lambda Deployment via Pipelines in Spinnaker. The plugin improves the existing implementation of functions in Spinnaker and introduces new stages to create, do traffic routing, and eventually delete the plugin. The current plugin lives here: [awslabs/aws-lambda-deployment-plugin-spinnaker)](https://github.com/awslabs/aws-lambda-deployment-plugin-spinnaker)

Description of what the plugin is.

### Acknowledgements

- [x] Source code will be available publicly on [`spinnaker-plugins`](https://github.com/spinnaker-plugins)
- [x] Donated code must explicitly declare a license
- [x] All authors listed below will be given `maintain` permissions to the plugin repository
- [x] Plugin authors are expected to continue as primary maintainers of plugin
- [x] Spinnaker core contributors are not expected to help maintain the plugin
- [x] Spinnaker core contributors will not automatically inherit permissions for plugin repository, with the exception of the Technical Oversight Committee for administrative purposes

### Maintainers

@gsapkal @wattdave @dkirillov @eyalmor94 @kevinawoo @zachsmith1 @c2tarun @awood45 @jasoncoffman @shyamsfo

**Comment by nimakaviani** [comment]
@ajordens @robzienert can we plz get some motion on this? thank you 🙂

**Comment by robzienert** [comment]
Just got back from vacation. Approved.

**Comment by ajordens** [comment]
The move to https://github.com/spinnaker-plugins/aws-account-registration-plugin-spinnaker is complete and the maintainers above should have WRITE access to the plugin repository.

**Comment by ajordens** [comment]
Let me know if there are any issues.

**Comment by nimakaviani** [comment]
great! thanks very much @ajordens @robzienert

**Comment by nimakaviani** [comment]
oh hmm 

> The move to https://github.com/spinnaker-plugins/aws-account-registration-plugin-spinnaker is complete and the maintainers above should have WRITE access to the plugin repository.

@ajordens just noticed from the above that the maintainers might be added to the wrong repo? this issue is for https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker and not the account registration plugin.

can you take a look and let me know? thanks!

**Comment by ajordens** [comment]
Ya, totally fat fingered that 👎 

Will be corrected momentarily.

**Comment by nimakaviani** [comment]
no worries 😄 and thanks!
