### ISSUE TITLE
REQUEST: New Reviewer status for micnncim

### ISSUE THREAD

**Issue by micnncim** [spinnaker/governance#198]
### Github Username

@micnncim

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @maggieneterval
- @ezimanyi

### List of qualifications for this position

https://github.com/pulls?q=is%3Apr+author%3Amicnncim+org%3Aspinnaker

**Comment by ezimanyi** [comment]
+1, @micnncim has made a number of great improvements!

**Comment by plumpy** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by micnncim** [comment]
Thank you all very much! Any update?

**Comment by ezimanyi** [comment]
Still waiting on approval from @robzienert @ethanfrogers .

**Comment by ajordens** [comment]
Majority approved.
