### ISSUE TITLE
REQUEST: New Reviewer status for KeisukeYamashita

### ISSUE THREAD

**Issue by KeisukeYamashita** [spinnaker/governance#199]
### Github Username

@KeisukeYamashita

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @maggieneterval
- @ezimanyi

### List of qualifications for this position

- https://github.com/pulls?q=is%3Apr+author%3AKeisukeYamashita+org%3Aspinnaker

**Comment by ajordens** [comment]
TOC +1

**Comment by ezimanyi** [comment]
+1 as sponsor and as TOC member, thanks for all the contributions!

**Comment by plumpy** [comment]
TOC +1

**Comment by maggieneterval** [comment]
+1

**Comment by KeisukeYamashita** [comment]
@ajordens Please take a look. Thank you in advance.

**Comment by ajordens** [comment]
TOC +1
