### ISSUE TITLE
REQUEST: New Reviewer status for pdk27

### ISSUE THREAD

**Issue by pdk27** [spinnaker/governance#201]
### Github Username
@pdk27

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @caseyhebebrand 
- @cfieber 

### List of qualifications for this position

- Links to public Spinnaker PRs
https://github.com/pulls?q=is%3Apr+author%3Apdk27+org%3Aspinnaker

**Comment by ezimanyi** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1, invited to the `oss-reviewers` team (check your email to accept)

**Comment by pdk27** [comment]
@robzienert @ajordens I still don't seem to have the permissions to add reviewers to my PRs. 

I have created a request for `approver` status - https://github.com/spinnaker/governance/issues/225 
Is there anything else I need to be able to add reviewers / merge my own PRs?
