### ISSUE TITLE
REQUEST: New Approver status for ncknt

### ISSUE THREAD

**Issue by ncknt** [spinnaker/governance#202]
### Github Username

@ncknt 

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Sponsored by 2 Approvers

### Sponsors

- @ethanfrogers 
- @kevinawoo

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Armory
- Links to public Spinnaker PRs: 
https://github.com/pulls?q=is%3Apr+author%3Ancknt+org%3Aspinnaker

**Comment by ezimanyi** [comment]
TOC +1

**Comment by kevinawoo** [comment]
👍 💯 10/10 A➕ would sponsor again!

**Comment by robzienert** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1, added you to the `oss-approvers` team. Hooray!

**Comment by ncknt** [comment]
Thank you all!
