### ISSUE TITLE
REQUEST: New Approver status for neil-yechenwei

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/governance#204]
### Github Username
@neil-yechenwei

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [ ] Sponsored by 2 Approvers

### Sponsors

- @mybayern1974
- @Grayzu

### List of qualifications for this position

- Links to public Spinnaker PRs
https://github.com/pulls?page=1&q=is%3Apr+author%3Aneil-yechenwei+org%3Aspinnaker

**Comment by ajordens** [comment]
This looks like the template for `Reviewer` status but is asking for `Approver`. There is already an outstanding invite for `Reviewer` due to your work on the Azure provider, going to close this issue.

To make the jump to `Approver`, you'll need sponsorship from two existing Approvers.
