### ISSUE TITLE
REQUEST: Nomination of Paul Roberts for the Steering Committee

### ISSUE THREAD

**Issue by pstout** [spinnaker/governance#211]
I hereby nominate Paul Roberts for a two year term on the Steering Committee starting February 1st, 2021 and ending January 31st, 2023.*

Paul Roberts is a Principal Architect at AWS and has been driving the OSS strategy across the Strategic Segment. He has been working with the Lambda, ECS, K8S, EC2, and OSS teams at AWS for the last 3 years advocating the importance of Spinnaker. His efforts led to Spinnaker contributions from AWS ranging from talks at industry conferences such as OSCon, re:Invent how-to workshops, adding functions support, strengthening ECS support, enhancements to Orca enabling new pipeline stages, Deck enhancements, and improving documentation to ease the installation on AWS. Paul has 20+ years of industry experience. He has held engineering positions at companies such Sun Microsystems where he built solutions to deploy and manage infrastructure deployments in data centers around the world. Additionally, Paul was the infrastructure engineering lead supporting a government agency responsible for the annual distribution of $500B worth of federal grants. He continues to be an active member of the community and meets regularly with Spinnaker users at AWS to ensure their experience with the project is frictionless.

Steering Committee members, please indicate your vote via a +1 for yes or a -1 for no or 0 for abstaining.

* - This seat is currently occupied by Peter Stout, whose term ends on January 31st, 2021.

**Comment by pstout** [comment]
+1

**Comment by duftler** [comment]
+1

**Comment by aglover** [comment]
An enthusiastic **+1** - bolded and extra large font.

**Comment by demobox** [comment]
+1
