### ISSUE TITLE
REQUEST: Nomination of Peter Stout (pstout) as SC Chair

### ISSUE THREAD

**Issue by aglover** [spinnaker/governance#212]
I hereby nominate Peter Stout (@pstout) to fill the balance of the term for the seat currently held by me (Andy Glover / @aglover) as I am resigning effective February 1st, 2021.  My term expires on January 31st, 2022.

Peter Stout is a technical director at Netflix where he works at the junction of business and technology.  He has been involved in setting the direction of the development of the Spinnaker project and its use within Netflix.  Peter has been a member the Steering Committee for the past three years.  During that time he has been an advocate for the transition of the project from being primarily driven by Netflix to being an integral part of the broader cloud and CI/CD open source community.
Steering Committee members, please indicate your vote via a +1 for yes or a -1 for no or 0 for abstaining.

**Comment by aglover** [comment]
+1!

**Comment by demobox** [comment]
+1

**Comment by pstout** [comment]
0 - I am not allowed to vote on my nomination.

**Comment by duftler** [comment]
+1

**Comment by imosquera** [comment]
+1
