### ISSUE TITLE
REQUEST: New Approver status for skandragon (Michael Graff)

### ISSUE THREAD

**Issue by skandragon** [spinnaker/governance#213]
### Github Username

@skandragon 

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @robzienert 
- @german-muzquiz 

### List of qualifications for this position

Currently at OpsMX, and while I've not been very active in the last year, my role is expanding to include Spinnaker once again.  Initially focused on the Kubernetes clouddriver, along with other Clouddriver performance enhancements.

Previously at Netflix on the spinnaker team.

https://github.com/pulls?page=2&q=is%3Apr+author%3Askandragon+org%3Aspinnaker

**Comment by ajordens** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1, added to `oss-approvers`
