### ISSUE TITLE
REQUEST: Nomination of Edgar Magana for the Steering Committee 

### ISSUE THREAD

**Issue by imosquera** [spinnaker/governance#216]
I hereby nominate Edgar Magana for a two year term on the Steering Committee starting February 1st, 2021 and ending January 31st, 2023.*

Edgar Magana is a Software Engineer Architect at Salesforce. Edgar is an emerging leader who has specialized in Cloud Computing, Micro-services, Network Virtualization, Software-defined Networking (SDN), CI/CD, Spinnaker, Network Functions Virtualization (NFV), OpenFlow and OpenStack. He is leading the Continuous Delivery platform at Salesforce for Public Cloud. He has developed excellent software development skills and outstanding customer and business driven experience. Edgar has strong experience in fully automated Cloud Computing deployments with the use of technologies such as Terraform, Helm, K8s and Spinnaker. He has led Spinnaker and OpenStack open-source development, third-party integration and deployment teams for over the last 15+ years.

Steering Committee members, please indicate your vote via a +1 for yes or a -1 for no or 0 for abstaining.

This seat was occupied by Andrew Phillips, whose term ended on January 31st, 2021.

**Comment by demobox** [comment]
+1

**Comment by duftler** [comment]
+1

**Comment by pstout** [comment]
Updated who this is assigned to match the current membership of the Spinnaker SC.  I need to figure out why Paul Roberts is not available to me as an assignee.  I will dig into that.

**Comment by pstout** [comment]
+1 on electing Edgar.

**Comment by pauljrob** [comment]
+1

**Comment by aglover** [comment]
+1!

**Comment by plumpy** [comment]
> starting February 1st, 2021 and ending January 31st, 2023.*

FYI, [the governance rules](https://github.com/spinnaker/governance/blob/master/governance.md#steering-committee) say that terms start on January 1st. I don't think we've been very good at paying attention to that on either the SC or TOC (where terms are supposed to start July 1st)... nor do we keep track of the actual terms for each member anywhere AFAIK.

But let's say Edgar's term ends on Dec 31, 2022? And I'll send a PR adding all the SC/TOC terms to [that page](https://github.com/spinnaker/governance/blob/master/governance.md#steering-committee)?

**Comment by plumpy** [comment]
@ajordens pointed out to me that the change in SC dates was [voted on in the SC meeting on 12/18](https://docs.google.com/document/d/1HMdwvBPM4uRFqoeAd7eEkVWIC8dQP40zFavOE5Kq-Eg/edit). I'll update the governance doc.

**Comment by pstout** [comment]
@plumpy I have a PR in the works to handle that.  I was waiting on Edgar's nomination to submit it.

**Comment by pstout** [comment]
@plumpy PR posted here: https://github.com/spinnaker/governance/pull/217.

**Comment by pstout** [comment]
With a majority of the Steering Committee having voted in favor, Eric Magana has been elected to the Steering Committee.
