### ISSUE TITLE
REQUEST: New Reviewer status for nimakaviani

### ISSUE THREAD

**Issue by nimakaviani** [spinnaker/governance#223]
### Github Username

e.g. @nimakaviani 

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @luispollo 
- @robfletcher x

### List of qualifications for this position

- https://github.com/spinnaker/keel/pulls?q=is%3Apr+author%3Animakaviani

**Comment by luispollo** [comment]
👍  from me!

**Comment by robzienert** [comment]
TOC +1

**Comment by emagana** [comment]
SC +1
