### ISSUE TITLE
REQUEST: New Reviewer status for @ranihorev

### ISSUE THREAD

**Issue by ranihorev** [spinnaker/governance#224]
### Github Username
@ranihorev

### Requirements

- [ ] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @luispollo 
- @christopherthielen 

### List of qualifications for this position

- https://github.com/spinnaker/deck/pull/8948
- https://github.com/spinnaker/deck/pull/8938
- https://github.com/spinnaker/deck/pull/8922
- https://github.com/spinnaker/deck/pull/8903
- https://github.com/spinnaker/deck/pull/8888

**Comment by ajordens** [comment]
TOC +1

**Comment by luispollo** [comment]
+1 from me!

**Comment by robzienert** [comment]
TOC +1
