### ISSUE TITLE
REQUEST: New Approver status for pdk27

### ISSUE THREAD

**Issue by pdk27** [spinnaker/governance#225]
### Github Username
@pdk27

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role - https://github.com/spinnaker/governance/issues/201 
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @caseyhebebrand
- @cfieber

### List of qualifications for this position

- Name of organization(s) with significant stake in project: aws
- Links to public Spinnaker PRs: https://github.com/pulls?q=is%3Apr+author%3Apdk27+org%3Aspinnaker

**Comment by cfieber** [comment]
big 👍 from me - I've seen some pretty significant refactors and enhancements from @pdk27 so far and looking forward to more

**Comment by caseyhebebrand** [comment]
Ditto to everything @cfieber said 👍. @pdk27 has been steadily contributing for about 6 months now and has some upcoming features in the works.

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by ajordens** [comment]
Majority approved!
