### ISSUE TITLE
REQUEST: New Approver status for zachsmith1

### ISSUE THREAD

**Issue by zachsmith1** [spinnaker/governance#229]
### Github Username

@zachsmith1

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @ncknt 
- @german-muzquiz  

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Armory
- Links to public Spinnaker PRs

https://github.com/spinnaker/clouddriver/pulls?q=author%3Azachsmith1
https://github.com/spinnaker/orca/pulls?q=author%3Azachsmith1

https://github.com/spinnaker/clouddriver/pulls?q=reviewed-by%3Azachsmith1+
https://github.com/spinnaker/orca/pulls?q=reviewed-by%3Azachsmith1
https://github.com/spinnaker/deck/pulls?q=reviewed-by%3Azachsmith1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1
