### ISSUE TITLE
REQUEST: New Approver status for ranihorev

### ISSUE THREAD

**Issue by ranihorev** [spinnaker/governance#230]
### Github Username

@ranihorev

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @christopherthielen 
- @caseyhebebrand 
- @erikmunson 

### List of qualifications for this position

- Name of organization(s) with significant stake in project - Netflix
- Links to public Spinnaker PRs - https://github.com/spinnaker/deck/pulls?q=is%3Apr+author%3Aranihorev

**Comment by ajordens** [comment]
> Has reviewed 5 PRs of significant scope

It'd be nice to see [reviews on other PRs](https://github.com/spinnaker/deck/pulls?q=is%3Apr+commenter%3Aranihorev+) in addition to your own merged PRs.

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1
