### ISSUE TITLE
REQUEST: New Reviewer status for @Bijnagte  

### ISSUE THREAD

**Issue by ajordens** [spinnaker/governance#232]
### Github Username

@Bijnagte 

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @ajordens
- @robzienert 

### List of qualifications for this position

- https://github.com/spinnaker/clouddriver/pulls?q=is%3Apr+author%3ABijnagte
- https://github.com/spinnaker/orca/pulls?q=is%3Apr+author%3ABijnagte

**Comment by ajordens** [comment]
@Bijnagte is a newly hired member of the Spinnaker team at Netflix and has hit the ground running!

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1
