### ISSUE TITLE
REQUEST: New Reviewer status for paragbhingre

### ISSUE THREAD

**Issue by paragbhingre** [spinnaker/governance#237]
### Github Username - 

paragbhingre

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @allisaurus 
- @piradeepk 

### List of qualifications for this position

- https://github.com/spinnaker/spinnaker/issues/6374
- https://github.com/spinnaker/orca/pull/4117
- https://github.com/spinnaker/clouddriver/pull/5314
- https://github.com/spinnaker/deck/pull/9092
- https://github.com/spinnaker/clouddriver/pull/5149
- https://github.com/spinnaker/gate/pull/1394
- https://github.com/spinnaker/clouddriver/pull/5258
- https://github.com/spinnaker/deck/pull/8875

**Comment by piradeepk** [comment]
+1

**Comment by allisaurus** [comment]
+1 😎

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1
