### ISSUE TITLE
REQUEST: New Approver status for dogonthehorizon

### ISSUE THREAD

**Issue by dogonthehorizon** [spinnaker/governance#240]
### Github Username

@dogonthehorizon

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @ncknt 
- @zachsmith1 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: @armory
- Links to public Spinnaker PRs
  - https://github.com/search?q=org%3Aspinnaker+is%3Aclosed+author%3Adogonthehorizon

Notable contributions:
- Refactored/reorganized plugin developer guide
- Hosted 2 workshops at previous Spinnaker Summits showing community members how to contribute
- Served as release manager for 1.23

**Comment by ajordens** [comment]
TOC +1
