### ISSUE TITLE
REQUEST: New Reviewer status for cristhian-castaneda

### ISSUE THREAD

**Issue by cristhian-castaneda** [spinnaker/governance#244]
### Github Username

@cristhian-castaneda

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon 
- @ncknt 

### List of qualifications for this position

- Links to public Spinnaker PRs
  - https://github.com/spinnaker/halyard/pull/1866
  - https://github.com/spinnaker/echo/pull/952
  - https://github.com/spinnaker/deck/pull/8287
  - https://github.com/spinnaker/gate/pull/1199
  - https://github.com/spinnaker/stats/pull/21
  - https://github.com/spinnaker/halyard/pull/1543
  - https://github.com/spinnaker/kork/pull/519

**Comment by ajordens** [comment]
TOC +1
