### ISSUE TITLE
REQUEST: New Approver status for nimakaviani

### ISSUE THREAD

**Issue by nimakaviani** [spinnaker/governance#254]
### Github Username

@nimakaviani 

### Requirements

- [X] Belongs to an organization with significant stake in project
- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Is already fulfilling the Reviewer role
- [X] Has reviewed 5 PRs of significant scope
- [X] Sponsored by 2 Approvers

### Sponsors

- @luispollo 
- @robfletcher 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: AWS
- Links to public Spinnaker PRs

Actively contributing to Keel. Contributed to multiple Spinnaker plugins related to managed delivery

- https://github.com/nimakaviani/managed-delivery-k8s-plugin
- https://github.com/nimakaviani/ci-build-plugin

**Comment by luispollo** [comment]
An excited 👍  from me!

**Comment by ajordens** [comment]
TOC +1
