### ISSUE TITLE
REQUEST: New Reviewer status for j-sandy

### ISSUE THREAD

**Issue by j-sandy** [spinnaker/governance#255]
### Github Username

@j-sandy

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @skandragon 
- @link108 

### List of qualifications for this position

- https://github.com/spinnaker/orca/pull/4155
- https://github.com/spinnaker/kork/pull/876
- https://github.com/spinnaker/front50/pull/1052
- https://github.com/spinnaker/kork/pull/878
- https://github.com/spinnaker/clouddriver/pull/5471
- https://github.com/spinnaker/halyard/pull/1890
- https://github.com/spinnaker/kork/pull/888
- https://github.com/spinnaker/kork/pull/887
- https://github.com/spinnaker/kork/pull/891
- https://github.com/spinnaker/kork/pull/892
- https://github.com/spinnaker/kork/pull/894

**Comment by ajordens** [comment]
TOC +1

**Comment by j-sandy** [comment]
Thanks !
