### ISSUE TITLE
REQUEST: New TOC member for link108

### ISSUE THREAD

**Issue by link108** [spinnaker/governance#258]
### Github Username
@link108

### Requirements

- [👍] I am a Spinnaker Approver already
- [👍] I have enabled 2FA on my Github account
- [👍] I have one sponsor within the Steering Committee
- [👍] I have spoken to my sponsor(s) ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @imosquera 

#### Prior open source exprience
- https://github.com/cdfoundation/standardized-metadata/pull/1
- https://github.com/helm/helm/pull/9623
- https://github.com/hashicorp/consul-template/pull/1337
- https://github.com/GiftRocket/giftrocket-ruby/pull/5
- https://github.com/GiftRocket/giftrocket-ruby/pull/2
- https://github.com/GiftRocket/giftrocket-ruby/pull/1
#### Links to public contributions showing your technical command of the Spinnaker project
- https://github.com/spinnaker/governance/pull/112
- https://github.com/spinnaker/governance/issues/28
- https://github.com/spinnaker/governance/blob/master/rfc/plugins.md
#### Any other qualifications
- [Spinnaker Summit 2019 Secret Engine](https://youtu.be/6MPEbg9gBXI?list=PL4yLrwUObNkvGzXKSEU8miQTlvZyZvXWq)
- [Spinnaker Summit 2019 Plugins](https://youtu.be/7EPr2N9cHj8?list=PL4yLrwUObNkvGzXKSEU8miQTlvZyZvXWq)
- [Spinnaker Summit 2020 Extensibility](https://youtu.be/kIDBAj2eDHQ?list=PL4yLrwUObNku4sn3eUScl_0GzC5HnYARf)
- [Spinnaker Summit 2020 Plugins Workshop](https://youtu.be/qDvaK77n6xs?list=PL4yLrwUObNku4sn3eUScl_0GzC5HnYARf)
- GSoC Mentor 2020 - [DroneCI Stage](https://summerofcode.withgoogle.com/archive/2020/projects/4813067126308864/)
- GSoC Mentor 2021 - [try.spinnaker.io](https://summerofcode.withgoogle.com/projects/#6024853804548096)

**Comment by plumpy** [comment]
TOC :+1: :100:

**Comment by duftler** [comment]
SC +1

**Comment by claymccoy** [comment]
+1

**Comment by pstout** [comment]
SC +1

If your sponsor votes, then this is good to go.

**Comment by imosquera** [comment]
+1

**Comment by plumpy** [comment]
Added you to `toc@spinnaker.io`, the TOC slack channel, and the TOC GitHub group.

Sent #263 to add you to this repo.

Welcome!
