### ISSUE TITLE
REQUEST: New Reviewer status for mattgogerly

### ISSUE THREAD

**Issue by mattgogerly** [spinnaker/governance#260]
### Github Username

@mattgogerly

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @zachsmith1 
- @german-muzquiz 

### List of qualifications for this position

- https://github.com/spinnaker/clouddriver/pull/5462
- https://github.com/spinnaker/clouddriver/pull/5427
- https://github.com/spinnaker/clouddriver/pull/5391
- https://github.com/spinnaker/clouddriver/pull/5416
- https://github.com/spinnaker/front50/pull/1036
- https://github.com/spinnaker/spinnaker-gradle-project/pull/170

**Comment by ajordens** [comment]
TOC +1
