### ISSUE TITLE
REQUEST: New Reviewer status for clanesf

### ISSUE THREAD

**Issue by clanesf** [spinnaker/governance#262]
### Github Username

@clanesf

### Requirements

- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Sponsored by 2 Approvers

### Sponsors

@emjburns - Emily Burns (Netflix)
@link108 - Cameron Motevasselani (Armory)

### List of qualifications for this position

[feat(cloudconfig): Externalize cloud config refresh interval and decouple from cache refresh interval](https://github.com/spinnaker/clouddriver/pull/4699)
[fix(ssl): pass TrustManager to okHttp SSL socketfactory for JDK9+](https://github.com/spinnaker/kork/pull/540)
[chore(authn/authz): Add logging for Fiat session filter to give error visibility.](https://github.com/spinnaker/gate/pull/974)
[feat:(provider/Kubernetes) Add ability to set deployment strategy for service settings #1370](https://github.com/spinnaker/halyard/pull/1370)
[feat(k8s/deploy): Add custom health check to service-settings](https://github.com/spinnaker/halyard/pull/1572)
[fix(artifacts): add more explicit information for pulling GitHub file](https://github.com/spinnaker/spinnaker.github.io/pull/552)
[docs(faq): Add examples of how to run Spinnaker servers behind an http proxy server](https://github.com/spinnaker/spinnaker.github.io/pull/1283)
[chore(docs) Documentation of Amazon SQS-SNS based pubsub](https://github.com/spinnaker/spinnaker.github.io/pull/1404)
[chore(docs/halyard/service-settings): Added extensive documentation regarding what can be configured for a Kubernetes deployment via service settings in halyard](https://github.com/spinnaker/spinnaker.github.io/pull/1447)

Presenter at Spinnaker Summit 2019 (Seattle), 2020(Summit Virtual) and 2021 (cdCon virtual)
Co-Lead of Spinnaker Kubernetes Provider SIG 01/2021 - Present

**Comment by ajordens** [comment]
TOC +1
