### ISSUE TITLE
REQUEST: New Reviewer status for @kirangodishala

### ISSUE THREAD

**Issue by kirangodishala** [spinnaker/governance#266]
### Github Username

@kirangodishala

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @skandragon 
- @dbyron-sf

### List of qualifications for this position

- Links to public Spinnaker PRs
https://github.com/spinnaker/clouddriver/pull/4202
https://github.com/spinnaker/clouddriver/pull/5125
https://github.com/spinnaker/clouddriver/pull/5295
https://github.com/spinnaker/clouddriver/pull/5382
https://github.com/spinnaker/spinnaker.io/pull/133 
https://github.com/spinnaker/clouddriver/pull/5512
https://github.com/spinnaker/spinnaker.io/pull/142

**Comment by dbyron-sf** [comment]
+1

**Comment by kirangodishala** [comment]
Thank you @dbyron-sf

**Comment by skandragon** [comment]
+1

**Comment by kirangodishala** [comment]
Thank you @skandragon

**Comment by ajordens** [comment]
TOC +1
