### ISSUE TITLE
REQUEST: New Reviewer status for deverton

### ISSUE THREAD

**Issue by deverton** [spinnaker/governance#269]
### Github Username

@deverton 

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dbyron-sf 
- @mattgogerly

### List of qualifications for this position

- https://github.com/spinnaker/orca/pull/4120
- https://github.com/spinnaker/orca/pull/3923
- https://github.com/spinnaker/clouddriver/pull/4936
- https://github.com/spinnaker/clouddriver/pull/5344
- https://github.com/spinnaker/clouddriver/pull/5009
- https://github.com/spinnaker/fiat/pull/828
- https://github.com/spinnaker/fiat/pull/830
- https://github.com/spinnaker/fiat/pull/835
- https://github.com/spinnaker/fiat/pull/838
- https://github.com/spinnaker/fiat/pull/845
- https://github.com/spinnaker/fiat/pull/849
- https://github.com/spinnaker/fiat/pull/854

**Comment by dbyron-sf** [comment]
+1

**Comment by mattgogerly** [comment]
+1 from me

**Comment by deverton** [comment]
Thanks @mattgogerly 🙇

**Comment by ajordens** [comment]
TOC +1
