### ISSUE TITLE
REQUEST: New Reviewer status for @apoorvmahajan

### ISSUE THREAD

**Issue by apoorvmahajan** [spinnaker/governance#270]
### Github Username

@apoorvmahajan

### Requirements

- [ ] Known active participant in the community
- [ ] Has submitted at least 5 PRs of significant scope that are merged
- [ ] Sponsored by 2 Approvers

### Sponsors

- @dbyron-sf
- @link108 

### List of qualifications for this position

- Links to public Spinnaker PRs
- https://github.com/spinnaker/clouddriver/pull/5401
- https://github.com/spinnaker/clouddriver/pull/5442
- https://github.com/spinnaker/clouddriver/pull/5444
- https://github.com/spinnaker/clouddriver/pull/5473
- https://github.com/spinnaker/clouddriver/pull/5500
- https://github.com/spinnaker/clouddriver/pull/5184
- https://github.com/spinnaker/orca/pull/4177
- https://github.com/spinnaker/clouddriver/pull/5515
- https://github.com/spinnaker/clouddriver/pull/5528
- https://github.com/spinnaker/clouddriver/pull/5530
- https://github.com/spinnaker/clouddriver/pull/5532
- https://github.com/spinnaker/orca/pull/4150
- https://github.com/spinnaker/deck/pull/9498

**Comment by dbyron-sf** [comment]
👍

**Comment by link108** [comment]
+1 from me, happy to sponsor

**Comment by apoorvmahajan** [comment]
Thank you @dbyron-sf and @link108!
