### ISSUE TITLE
REQUEST: New Approver status for mattgogerly

### ISSUE THREAD

**Issue by mattgogerly** [spinnaker/governance#277]
### Github Username

@mattgogerly

### Requirements

- [X] Belongs to an organization with significant stake in project
- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Is already fulfilling the Reviewer role
- [X] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @dbyron-sf 
- @zachsmith1 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: JPMorgan Chase

- Reviews:
https://github.com/spinnaker/orca/pull/4177
https://github.com/spinnaker/clouddriver/pull/5581
https://github.com/spinnaker/front50/pull/1072
https://github.com/spinnaker/deck/pull/9633
https://github.com/spinnaker/fiat/pull/877
https://github.com/spinnaker/clouddriver/pull/5475
https://github.com/spinnaker/orca/pull/4138

- Links to public Spinnaker PRs:
https://github.com/spinnaker/clouddriver/pull/5577
https://github.com/spinnaker/clouddriver/pull/5548
https://github.com/spinnaker/clouddriver/pull/5508
https://github.com/spinnaker/clouddriver/pull/5462
https://github.com/spinnaker/clouddriver/pull/5427
https://github.com/spinnaker/clouddriver/pull/5416
https://github.com/spinnaker/clouddriver/pull/5391
https://github.com/spinnaker/deck/pull/9771
https://github.com/spinnaker/spinnaker-gradle-project/pull/170

**Comment by dbyron-sf** [comment]
@mattgogerly I'm happy to be one of your sponsors.  Do you have another in mind?

**Comment by mattgogerly** [comment]
> @mattgogerly I'm happy to be one of your sponsors. Do you have another in mind?

Thanks! Was going to ask one of the folks at Armory but haven't got round to it yet.

**Comment by link108** [comment]
LGTM +1
