### ISSUE TITLE
REQUEST: New Reviewer status for sanopsmx

### ISSUE THREAD

**Issue by sanopsmx** [spinnaker/governance#279]
### Github Username

@sanopsmx 

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @skandragon 
- @dbyron-sf 

### List of qualifications for this position

- Links to public Spinnaker PRs
- https://github.com/spinnaker/deck/pull/8779
- https://github.com/spinnaker/orca/pull/3988
- https://github.com/spinnaker/fiat/pull/512
- https://github.com/spinnaker/gate/pull/1483
- https://github.com/spinnaker/orca/pull/4183

**Comment by plumpy** [comment]
TOC +1

**Comment by dbyron-sf** [comment]
+1 from me.

**Comment by skandragon** [comment]
+1 from me
