### ISSUE TITLE
REQUEST: Nomination of Isaac Mosquera for Another Term on the Steering Committee

### ISSUE THREAD

**Issue by pstout** [spinnaker/governance#282]
I nominate Isaac Mosquera for another term on the Steering Committee. Isaac's current term ends on 1/31/2022.

Isaac Mosquera is CTO & Co-Founder of Armory. He has been leading an engineering and product team engaged in the Spinnaker community for three years.  Prior to this, he spent 20 years architecting large-scale systems at companies such as ShareThis, Socialize and XM Satellite Radio, as well as creating high scalability/load websites for brands such as Games Radar by Future Publishing.  He co-founded Armory to help enterprises innovate through happy & productive engineering teams.

Steering Committee members, please indicate you vote via a +1 for yes or a -1 for no or 0 for abstaining.  As per the Spinnaker project’s rules, Isaac does not have a vote on his election.

**Comment by pstout** [comment]
+1

**Comment by emagana** [comment]
+1

**Comment by pauljrob** [comment]
+1 - I fully support this.

**Comment by duftler** [comment]
+1

**Comment by link108** [comment]
Closing in favor of https://github.com/spinnaker/governance/pull/312
