### ISSUE TITLE
REQUEST: Nomination of Amy Smidutz as SC Chair

### ISSUE THREAD

**Issue by pstout** [spinnaker/governance#283]
I hereby nominate Amy Smidutz for a two year term on the Steering Committee starting February 1st, 2022 and ending January 31st, 2024.*

Amy Smidutz leads Delivery Engineering at Netflix.  As a senior technology leader, she has worked in a variety of platform spaces over the last 15 years, including continuous delivery, micro-services, network infrastructure, cloud computing, big data, and reliability.  Delivery Engineering is responsible for Spinnaker, Jenkins, and Infrastructure Experimentation platforms handling safe delivery of assets from commit to production.  She is passionate about building engineering teams that create exceptional software and loves curating great environments for teams to do amazing work while having fun.

Steering Committee members, please indicate your vote via a +1 for yes or a -1 for no or 0 for abstaining.

* - This seat is currently occupied by Peter Stout, whose term ends on January 31st, 2022.

**Comment by pstout** [comment]
+1

**Comment by emagana** [comment]
+1

**Comment by duftler** [comment]
+1

**Comment by pauljrob** [comment]
+1 - excited to partner with Amy!

**Comment by link108** [comment]
Closing in favor of https://github.com/spinnaker/governance/pull/312, I'm happy to saw @asmidutz is part of the new TOC 🥳
