### ISSUE TITLE
Nomination of Gopinath Rebala for Steering Committee 

### ISSUE THREAD

**Issue by balajisiva** [spinnaker/governance#285]
I nominate Gopinath Rebala for the Steering Committee.

Gopinath Rebala is CTO of OpsMx, a long-term Spinnaker contributor. OpsMx is a staunch supporter of Spinnaker and has contributed significantly to Spinnaker functionality. OpsMx is contributing significantly to resolving security vulnerabilities in Spinnaker components and enhancing Clouddriver for GCP among other areas of Spinnaker. As part of OpsMx, Gopinath has worked with various large end-users in helping them with the rollout of Spinnaker. He is passionate about creating real-world solutions with exceptional software. He is a frequent speaker at the Meetups, Spinnaker summit, and CDCon conferences. 

Steering Committee members, please indicate you vote via a +1 for yes or a -1 for no or 0 for abstaining.

**Comment by duftler** [comment]
My term on the SC expired several days ago, but I'd like to express my (non-voting) support for Gopinath as a member of the Steering Committee. Has has been engaged for a long time with the Spinnaker community (I can remember quite a few conversations at meetups over the years), and his company continues to make significant contributions in the space.

**Comment by plumpy** [comment]
As a TOC member, I'd also stronly support adding Gopinath to the steering committee. We've worked with him at Google on various GCP-related features and I think he could bring a welcome perspective to the Spinnaker community.

**Comment by emagana** [comment]
+1

**Comment by skandragon** [comment]
I don't have voting rights, but I would love to see Gopi on the committee.  I've worked with him now for several years, and he's very level headed and community focused.

**Comment by balajisiva** [comment]
Is there a decision on this nomination?  @emagana

**Comment by link108** [comment]
Closing in favor of https://github.com/spinnaker/governance/pull/312, I'm happy to report @rebalag is part of the new TOC 🥳
