### ISSUE TITLE
REQUEST: New Approver status for j-sandy

### ISSUE THREAD

**Issue by j-sandy** [spinnaker/governance#290]
### Github Username

@j-sandy

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @skandragon 
- @dbyron-sf 
- @plumpy 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: OpsMx
- Reviews:
   https://github.com/spinnaker/kork/pull/912
   https://github.com/spinnaker/deck/pull/9721
   https://github.com/spinnaker/halyard/pull/1913
   https://github.com/spinnaker/echo/pull/1135
   https://github.com/spinnaker/front50/pull/1052
   https://github.com/spinnaker/clouddriver/pull/5589
   https://github.com/spinnaker/orca/pull/4183
   https://github.com/spinnaker/gate/pull/1483
- Links to public Spinnaker PRs:
   https://github.com/spinnaker/kork/pull/946
   https://github.com/spinnaker/kork/pull/943
   https://github.com/spinnaker/front50/pull/1104
   https://github.com/spinnaker/igor/pull/997
   https://github.com/spinnaker/fiat/pull/923
   https://github.com/spinnaker/front50/pull/1103
   https://github.com/spinnaker/echo/pull/1158
   https://github.com/spinnaker/halyard/pull/1936
   https://github.com/spinnaker/rosco/pull/854
   https://github.com/spinnaker/clouddriver/pull/5652
   https://github.com/spinnaker/orca/pull/4231
   https://github.com/spinnaker/front50/pull/1096
   https://github.com/spinnaker/gate/pull/1505
   https://github.com/spinnaker/clouddriver/pull/5586
   https://github.com/spinnaker/clouddriver/pull/5585
   https://github.com/spinnaker/orca/pull/4194
   https://github.com/spinnaker/kork/pull/895
   https://github.com/spinnaker/orca/pull/4185
   https://github.com/spinnaker/rosco/pull/812
   https://github.com/spinnaker/kork/pull/894
   https://github.com/spinnaker/gate/pull/1480
   https://github.com/spinnaker/kork/pull/892
   https://github.com/spinnaker/kork/pull/891
   https://github.com/spinnaker/kork/pull/888
   https://github.com/spinnaker/orca/pull/4155
   https://github.com/spinnaker/kork/pull/876
   https://github.com/spinnaker/front50/pull/1052
   https://github.com/spinnaker/kork/pull/878
   https://github.com/spinnaker/clouddriver/pull/5471
   https://github.com/spinnaker/kork/pull/887
   https://github.com/spinnaker/halyard/pull/1890

**Comment by skandragon** [comment]
I'm happy to sponsor you.

**Comment by j-sandy** [comment]
Thank you @skandragon !

**Comment by dbyron-sf** [comment]
+1 for me

**Comment by plumpy** [comment]
+1

**Comment by dbyron-sf** [comment]
added to approvers in https://github.com/spinnaker/governance/commit/32e9cc854873b1f6ec894a5d15c00d730111d5c3
