### ISSUE TITLE
REQUEST: New Approver status for xibz

### ISSUE THREAD

**Issue by xibz** [spinnaker/governance#298]
### Github Username

@xibz

### Requirements

- [ x] Belongs to an organization with significant stake in project
- [x ] Known active participant in the community
- [ ] Has submitted at least 5 PRs of significant scope that are merged
- [x ] Is already fulfilling the Reviewer role
- [ x] Has reviewed 5 PRs of significant scope (At least indirectly. As in reviewing a PR internally before it being submitted to upstream)
- [ x] Sponsored by 2 Approvers

### Sponsors

- @link108 
- @dbyron-sf 

### List of qualifications for this position

I am a Software Engineer at Apple on the Spinnaker team. As the name implies we have a heavy stake in Spinnaker.
PRs Ive submitted https://github.com/search?q=org%3Aspinnaker+is%3Apr+author%3Axibz

I know I dont have all the checkboxes, but Ive talked with Cameron during cdCon about some of the benefits of having me as an approver, mostly around breaking changes, documentation, and testing.

**Comment by link108** [comment]
@xibz re: our slack conversation a while ago, do you mind changing this to be reviewer? 🙏

**Comment by xibz** [comment]
Sure, I'll create a new request for reviewer tomorrow
