### ISSUE TITLE
REQUEST: New Reviewer status for nemesisOsorio

### ISSUE THREAD

**Issue by nemesisOsorio** [spinnaker/governance#300]
### Github Username

@nemesisOsorio

### Requirements

- [ ] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon 
- @link108 

### List of qualifications for this position

- https://github.com/spinnaker/clouddriver/pull/5593
- https://github.com/spinnaker/clouddriver/pull/5623
- https://github.com/spinnaker/clouddriver/pull/5726
- https://github.com/spinnaker/clouddriver/pull/5733
- https://github.com/spinnaker/clouddriver/pull/5741

**Comment by link108** [comment]
+1 from me!

**Comment by dogonthehorizon** [comment]
+1 approved

**Comment by dbyron-sf** [comment]
+1 from me (TOC).

**Comment by link108** [comment]
Thank you @nemesisOsorio for the PR, I've merged that, so I'm closing this issue 👍
