### ISSUE TITLE
PROPOSAL: New Cloud Provider for Google Cloud Run

### ISSUE THREAD

**Issue by kirangodishala** [spinnaker/governance#302]
### Cloud Provider

Google Cloud Run

### Maintaining Organization(s)

OpsMx

#### Point of Contact(s)

@sanopsmx @j-sandy @kirangodishala

### Requirements

- [x] Cloud Provider will be actively backed by a development team from Maintainers with a significant stake in the project.
- [x] Maintainers commit to triaging and addressing major bugs and issues with the integration in a timely manner.
- [x] Maintainers commit to handling routine maintainence tasks for the integrations, such as:
  - [x] Keeping it compatible with updates to the cloud provider itself.
  - [x] Making any cloud provider-specific changes in response to global architecture changes within Spinnaker.
- [x] Maintainers acknowledge failure to maintain cloud provider integration may prompt removal of integration from Spinnaker.
- [x] Maintainers agree to setup and maintain a Special Interest Group for the Cloud Provider integration.

**Comment by link108** [comment]
+1 from me!

**Comment by dbyron-sf** [comment]
+1 for me.

**Comment by mattgogerly** [comment]
+1

**Comment by mat-613** [comment]
+1

**Comment by jasonmcintosh** [comment]
+1 :)

**Comment by angeliski** [comment]
Hey team! @sanopsmx @j-sandy Is possible to send a link for the docs? We want to enable that in our org

**Comment by kirangodishala** [comment]
@angeliski - the documention is not pushed to Spinnaker.io. But you can add credetials to the config file as hown below similar to google compute, which should allow you explore the feature. @sanopsmx can provide more deatails like how to naigate to the screen to supply manifest etc?
```
    cloudrun:
      enabled: true
      accounts: []
```

**Comment by angeliski** [comment]
Thanks @kirangodishala 

I will try to setup, if you can provide the manifests will be really helpful

**Comment by sanopsmx** [comment]
> Thanks @kirangodishala
> 
> I will try to setup, if you can provide the manifests will be really helpful

@angeliski Please find the cloudrun document. Configuration and sample service yamls provided.
Please let us know if you are stuck, We are happy to help you.

[Cloud Run Implementation Guide.docx](https://github.com/spinnaker/governance/files/15199579/Cloud.Run.Implementation.Guide.docx)
[Cloud Run Implementation Guide.pdf](https://github.com/spinnaker/governance/files/15199580/Cloud.Run.Implementation.Guide.pdf)

**Comment by kirangodishala** [comment]
Closing the issue as the implementation is completed.
