### ISSUE TITLE
REQUEST: New Reviewer status for armory-abedonik

### ISSUE THREAD

**Issue by armory-abedonik** [spinnaker/governance#307]
### Github Username

@armory-abedonik

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon 
- @link108

### List of qualifications for this position

- https://github.com/spinnaker/orca/pull/4295
- https://github.com/spinnaker/front50/pull/1142
- https://github.com/spinnaker/fiat/pull/964
- https://github.com/spinnaker/fiat/pull/963
- https://github.com/spinnaker/orca/pull/4280
- https://github.com/spinnaker/deck/pull/9868
- https://github.com/spinnaker/rosco/pull/891

**Comment by dogonthehorizon** [comment]
+1 from me

**Comment by link108** [comment]
+1 from me!

**Comment by link108** [comment]
closing, as https://github.com/spinnaker/governance/pull/316 is now merged 🎉
