### ISSUE TITLE
REQUEST: New Reviewer status for jasonmcintosh

### ISSUE THREAD

**Issue by jasonmcintosh** [spinnaker/governance#308]
### Github Username
@jasonmcintosh 

### Requirements

- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Sponsored by 2 Approvers

### Sponsors

@link108
@dogonthehorizon
@mattgogerly
@jvz

### List of qualifications for this position

- [Links to public Spinnaker PRs](https://github.com/search?q=org%3Aspinnaker+is%3Apr+author%3Ajasonmcintosh)

**Comment by dogonthehorizon** [comment]
+1 from me!

**Comment by jvz** [comment]
+1 from me

**Comment by link108** [comment]
+1 from me!

**Comment by dbyron-sf** [comment]
+1

**Comment by jasonmcintosh** [comment]
https://github.com/spinnaker/governance/pull/311 :)

**Comment by link108** [comment]
Thank you! closing
