### ISSUE TITLE
REQUEST: New Reviewer status for mrampton

### ISSUE THREAD

**Issue by mrampton** [spinnaker/governance#309]
### Github Username

@mrampton

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon
- @link108 

### List of qualifications for this position

- https://github.com/spinnaker/spinnaker.github.io/pull/1592
- https://github.com/spinnaker/spinnaker.github.io/pull/1584
- https://github.com/spinnaker/spinnaker.github.io/pull/1572
- https://github.com/spinnaker/orca/pull/3260
- https://github.com/spinnaker/clouddriver/pull/3958
- https://github.com/spinnaker/clouddriver/pull/3957
- https://github.com/spinnaker/clouddriver/pull/3917
- https://github.com/spinnaker/clouddriver/pull/3912
- https://github.com/spinnaker/halyard/pull/1353
- https://github.com/spinnaker/spinnaker.github.io/pull/1398
- https://github.com/spinnaker/deck/pull/7099
- https://github.com/spinnaker/clouddriver/pull/3388
- https://github.com/spinnaker/clouddriver/pull/3297
- https://github.com/spinnaker/clouddriver/pull/3293
- https://github.com/spinnaker/clouddriver/pull/3292
- https://github.com/spinnaker/clouddriver/pull/3291
- https://github.com/spinnaker/igor/pull/314
- https://github.com/spinnaker/igor/pull/313
- https://github.com/spinnaker/clouddriver/pull/2890
- https://github.com/spinnaker/spinnaker.github.io/pull/911

**Comment by link108** [comment]
+1  🎉

**Comment by dbyron-sf** [comment]
+1

**Comment by mattgogerly** [comment]
+1

**Comment by link108** [comment]
closing, as https://github.com/spinnaker/governance/pull/315 is now merged 🎉
