### ISSUE TITLE
REQUEST: New Reviewer status for ovidiupopa07

### ISSUE THREAD

**Issue by ovidiupopa07** [spinnaker/governance#310]
### Github Username

@ovidiupopa07

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon 
- @link108 

### List of qualifications for this position

- https://github.com/spinnaker/spinnaker.io/pull/233
- https://github.com/spinnaker/orca/pull/4294
- https://github.com/spinnaker/igor/pull/1038
- https://github.com/spinnaker/deck/pull/9871
- https://github.com/spinnaker/deck/pull/9859
- https://github.com/spinnaker/deck/pull/9888
- https://github.com/spinnaker/clouddriver/pull/5791
- https://github.com/spinnaker/clouddriver/pull/5792
- https://github.com/spinnaker/clouddriver/pull/5795
- https://github.com/spinnaker/halyard/pull/1984

**Comment by dogonthehorizon** [comment]
+1 from me!

**Comment by dbyron-sf** [comment]
+1 from me.

**Comment by link108** [comment]
+1 from me!

**Comment by mattgogerly** [comment]
+1

**Comment by link108** [comment]
closing, as https://github.com/spinnaker/governance/pull/314 is now merged 🎉
