### ISSUE TITLE
REQUEST: New Approver status for ovidiupopa07

### ISSUE THREAD

**Issue by ovidiupopa07** [spinnaker/governance#321]
### Github Username

@ovidiupopa07 

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon 
- @link108 

### List of qualifications for this position

- Name of organization(s) with significant stake in project

   - Armory

- Links to public Spinnaker PRs

   - https://github.com/spinnaker/spinnaker.io/pull/278
   - https://github.com/spinnaker/front50/pull/1176
   - https://github.com/spinnaker/deck/pull/9911
   - https://github.com/spinnaker/orca/pull/4332
   - https://github.com/spinnaker/clouddriver/pull/5811
   - https://github.com/spinnaker/spinnaker/issues/6751
   - https://github.com/spinnaker/spinnaker.io/pull/262
   - https://github.com/spinnaker/clouddriver/pull/5803
   - https://github.com/spinnaker/halyard/pull/1984
   - https://github.com/spinnaker/clouddriver/pull/5795
   - https://github.com/spinnaker/clouddriver/pull/5792
   - https://github.com/spinnaker/clouddriver/pull/5791
   - https://github.com/spinnaker/deck/pull/9888
   - https://github.com/spinnaker/spinnaker.io/pull/233
   - https://github.com/spinnaker/orca/pull/4294
   - https://github.com/spinnaker/igor/pull/1038
   - https://github.com/spinnaker/deck/pull/9871
   - https://github.com/spinnaker/deck/pull/9859

- Reviews
{
https://github.com/spinnaker/rosco/pull/916,
https://github.com/spinnaker/rosco/pull/914,
https://github.com/spinnaker/rosco/pull/912,
https://github.com/spinnaker/rosco/pull/911,
https://github.com/spinnaker/deck/pull/9924,
https://github.com/spinnaker/deck/pull/9923,
https://github.com/spinnaker/deck/pull/9914,
https://github.com/spinnaker/deck/pull/9910,
https://github.com/spinnaker/deck/pull/9886,
https://github.com/spinnaker/deck/pull/9884,
https://github.com/spinnaker/orca/pull/4353,
https://github.com/spinnaker/orca/pull/4336,
https://github.com/spinnaker/orca/pull/4323,
https://github.com/spinnaker/front50/pull/1172,
https://github.com/spinnaker/front50/pull/1142
https://github.com/spinnaker/igor/pull/1053,
https://github.com/spinnaker/clouddriver/pull/5813
 'total': 17
 }

**Comment by dogonthehorizon** [comment]
+1 from me :D

**Comment by mattgogerly** [comment]
+1

**Comment by link108** [comment]
+1 from me!
