### ISSUE TITLE
REQUEST: New Reviewer status for edgarulg

### ISSUE THREAD

**Issue by edgarulg** [spinnaker/governance#323]
### Github Username

@edgarulg

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @link108 
- @dogonthehorizon 

### List of qualifications for this position

- https://github.com/spinnaker/igor/pull/1053
- https://github.com/spinnaker/kayenta/pull/866
- https://github.com/spinnaker/orca/pull/4219
- https://github.com/spinnaker/orca/pull/4218
- https://github.com/spinnaker/kayenta/pull/857
- https://github.com/spinnaker/rosco/pull/825
- https://github.com/spinnaker/orca/pull/4201
- https://github.com/spinnaker/igor/pull/975
- https://github.com/spinnaker/front50/pull/1082
- https://github.com/spinnaker/fiat/pull/891
- https://github.com/spinnaker/echo/pull/1137
- https://github.com/spinnaker/clouddriver/pull/5592
- https://github.com/spinnaker/gate/pull/1491
- https://github.com/spinnaker/clouddriver/pull/5566
- https://github.com/spinnaker/orca/pull/4134
- https://github.com/spinnaker/echo/pull/1078
- https://github.com/spinnaker/orca/pull/4046
- https://github.com/spinnaker/kleat/pull/161
- https://github.com/spinnaker/spinnaker/issues/6298
- https://github.com/spinnaker/orca/pull/4037
- https://github.com/spinnaker/orca/pull/3945
- https://github.com/spinnaker/spinnaker-gradle-project/pull/150
- https://github.com/spinnaker/gate/pull/1324
- https://github.com/spinnaker/front50/pull/930
- https://github.com/spinnaker/deck/pull/8507
- https://github.com/spinnaker/clouddriver/pull/4815
- https://github.com/spinnaker/orca/pull/3859
- https://github.com/spinnaker/kork/pull/741
- https://github.com/spinnaker/kork/pull/703
- https://github.com/spinnaker/orca/pull/3771
- https://github.com/spinnaker/spinnaker.github.io/pull/1885
- https://github.com/spinnaker/spinnaker.github.io/pull/1884
- https://github.com/spinnaker/spinnaker-gradle-project/pull/142
- https://github.com/spinnaker/gate/pull/1213
- https://github.com/spinnaker/kork/pull/657
- https://github.com/spinnaker/halyard/pull/1678
- https://github.com/spinnaker/deck/pull/8277
- https://github.com/spinnaker/orca/pull/3627

**Comment by link108** [comment]
+1 from me!

**Comment by dogonthehorizon** [comment]
+1 from me as well
