### ISSUE TITLE
REQUEST: New Reviewer status for DanielaS12

### ISSUE THREAD

**Issue by DanielaS12** [spinnaker/governance#326]
### Github Username

DanielaS12

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @link108
- @dogonthehorizon

### List of qualifications for this position

- Links to public Spinnaker PRs
- https://github.com/spinnaker/deck/pull/9928
- https://github.com/spinnaker/deck/pull/9923
- https://github.com/spinnaker/orca/pull/4353
- https://github.com/spinnaker/rosco/pull/916
- https://github.com/spinnaker/orca/pull/4336
- https://github.com/spinnaker/orca/pull/4335
- https://github.com/spinnaker/deck/pull/9910
- https://github.com/spinnaker/deck/pull/9909
- https://github.com/spinnaker/deck/pull/9896
- https://github.com/spinnaker/deck/pull/9884

**Comment by DanielaS12** [comment]
any update?

**Comment by link108** [comment]
+1 from me!
