### ISSUE TITLE
REQUEST: New Reviewer status for OscarMichelH

### ISSUE THREAD

**Issue by OscarMichelH** [spinnaker/governance#327]
### OscarMichelH

e.g. @OscarMichelH

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon 
- @link108

### List of qualifications for this position

https://github.com/spinnaker/orca/pull/4307
https://github.com/spinnaker/orca/pull/4312
https://github.com/spinnaker/deck/pull/9922
https://github.com/spinnaker/clouddriver/pull/5856
https://github.com/spinnaker/orca/pull/4368

**Comment by dogonthehorizon** [comment]
+1 from me

**Comment by OscarMichelH** [comment]
waiting

**Comment by link108** [comment]
+1 from me! Thank you!
