### ISSUE TITLE
REQUEST: New Reviewer status for sergio-quintero

### ISSUE THREAD

**Issue by sergio-quintero** [spinnaker/governance#328]
### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @dogonthehorizon 
- @link108

### List of qualifications for this position

- Links to public Spinnaker PRs

- https://github.com/spinnaker/echo/pull/1225
- https://github.com/spinnaker/echo/pull/1224
- https://github.com/spinnaker/deck/pull/9924
- https://github.com/spinnaker/orca/pull/4347
- https://github.com/spinnaker/echo/pull/1219
- https://github.com/spinnaker/kayenta/pull/916
- https://github.com/spinnaker/rosco/pull/911
- https://github.com/spinnaker/clouddriver/pull/5784
- https://github.com/spinnaker/deck/pull/9865
- https://github.com/spinnaker/clouddriver/pull/5615

**Comment by link108** [comment]
✅  plus one from me!

**Comment by dogonthehorizon** [comment]
+1 from me
