### ISSUE TITLE
REQUEST: New Reviewer status for jvz

### ISSUE THREAD

**Issue by jvz** [spinnaker/governance#330]
### Github Username

@jvz

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @link108
- @dbyron-sf

### List of qualifications for this position

- https://github.com/spinnaker/kork/pull/992
- https://github.com/spinnaker/kork/pull/974
- https://github.com/spinnaker/fiat/pull/966
- https://github.com/spinnaker/kork/pull/971
- https://github.com/spinnaker/clouddriver/pull/5719
- https://github.com/spinnaker/clouddriver/pull/5666
- https://github.com/spinnaker/kork/pull/942
- I've got a lot more, but you get the idea

**Comment by dbyron-sf** [comment]
+1 from me.

**Comment by jasonmcintosh** [comment]
+1 ;)

**Comment by link108** [comment]
+1 from me! 🥳
