### ISSUE TITLE
REQUEST: New Approver status for edgarulg

### ISSUE THREAD

**Issue by edgarulg** [spinnaker/governance#338]
### Github Username

@edgarulg 

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [ ] Has reviewed 5 PRs of significant scope
- [ ] Sponsored by 2 Approvers

### Sponsors

- @link108 
- @dogonthehorizon 
- @jasonmcintosh 
- @dbyron-sf 

### List of qualifications for this position

- Armory, Inc.
- [Links to public Spinnaker PRs](https://github.com/search?q=org%3Aspinnaker+is%3Apr+author%3Aedgarulg)

**Comment by link108** [comment]
+1 from me! 🥳

**Comment by dbyron-sf** [comment]
+1

**Comment by link108** [comment]
closing as this is now done!
