### ISSUE TITLE
REQUEST: New Approver status for kirangodishala

### ISSUE THREAD

**Issue by kirangodishala** [spinnaker/governance#342]
### Github Username
@kirangodishala

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [ ] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @dbyron-sf 
- @xibz 

### List of qualifications for this position

- Name of organization(s) with significant stake in project
   - OpsMx
- Links to public Spinnaker PRs
   - https://github.com/spinnaker/clouddriver/pull/5866
   - https://github.com/spinnaker/plugins/pull/4
   - https://github.com/spinnaker/plugins/pull/3
   - https://github.com/spinnaker/spinnaker.io/pull/269
   - https://github.com/spinnaker/clouddriver/pull/5793
   - https://github.com/spinnaker/clouddriver/pull/5773
   - https://github.com/spinnaker/kork/pull/976
   - https://github.com/spinnaker/clouddriver/pull/5747
   - https://github.com/spinnaker/spinnaker.io/pull/202
   - https://github.com/spinnaker/kork/pull/960
   - https://github.com/spinnaker/halyard/pull/1954
   - https://github.com/spinnaker/clouddriver/pull/5718
   - https://github.com/spinnaker/spinnaker.io/pull/181
   - https://github.com/spinnaker/clouddriver/pull/5512
   - https://github.com/spinnaker/spinnaker.io/pull/133
   - https://github.com/spinnaker/clouddriver/pull/5382
   - https://github.com/spinnaker/clouddriver/pull/5125
   - https://github.com/spinnaker/clouddriver/pull/4202
   - https://github.com/spinnaker/clouddriver/pull/5751

**Comment by dbyron-sf** [comment]
+1 from me!

**Comment by xibz** [comment]
+1 from me as well! Will really help with the cloud SIG too :)
