### ISSUE TITLE
REQUEST: New Reviewer status for xibz

### ISSUE THREAD

**Issue by xibz** [spinnaker/governance#347]
### Github Username

@xibz 

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

-  @dbyron-sf 
-  @link108 

### List of qualifications for this position
This is just kork, but there's PRs for all the other services too, but these should suffice.
https://github.com/spinnaker/kork/commits/master?author=xibz

**Comment by dbyron-sf** [comment]
+1 from me!

**Comment by dbyron-sf** [comment]
@xibz can you make a PR adding you to https://github.com/spinnaker/governance/blob/master/membership.yml please?

**Comment by link108** [comment]
+1 from me 🎉
