### ISSUE TITLE
REQUEST: New Reviewer status for @allisaurus

### ISSUE THREAD

**Issue by allisaurus** [spinnaker/governance#81]
### Github Username

@allisaurus

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @clareliguori 
- @robzienert 

### List of qualifications for this position

https://github.com/spinnaker/orca/pull/3016
https://github.com/spinnaker/clouddriver/pull/3825
https://github.com/spinnaker/deck/pull/7162
https://github.com/spinnaker/deck/pull/7338
https://github.com/spinnaker/spinnaker.github.io/pull/1452

smaller fixes/enhancements:
https://github.com/spinnaker/deck/pull/7123
https://github.com/spinnaker/deck/pull/7169
https://github.com/spinnaker/deck/pull/7170
https://github.com/spinnaker/kork/pull/412

**Comment by plumpy** [comment]
TOC +1!

**Comment by ethanfrogers** [comment]
TOC +1!!

**Comment by robzienert** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1
