### ISSUE TITLE
REQUEST: New Approver status for anotherchrisberry

### ISSUE THREAD

**Issue by anotherchrisberry** [spinnaker/governance#83]
### Github Username

@anotherchrisberry

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @ajordens
- @asher 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Netflix
- Links to public Spinnaker PRs: there are a few

**Comment by ethanfrogers** [comment]
TOC +1. Welcome back @anotherchrisberry!

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
I have the facts and I'm voting yes.

TOC +1

**Comment by duftler** [comment]
ha

**Comment by gcomstock** [comment]
You're all letting him off way too easily.

**Comment by ajordens** [comment]
TOC +1
