### ISSUE TITLE
REQUEST: Nomination of Erin Kidwell for the Steering Committee

### ISSUE THREAD

**Issue by aglover** [spinnaker/governance#86]
I nominate Erin Kidwell to replace Ruslan Meshenberg on the Steering Committee. Ruslan's term ends on 12/31/2019. 

Erin is the Director of Engineering Tools and Services at Netflix. Her team works closely with Delivery Engineering to reduce the complexity of building and integrating code across the growing polyglot ecosystem at Netflix. As a key stakeholder and trusted partner, Erin has played a vital role in the evolution of Spinnaker. I'm excited at the prospects of Erin joining the SC as she brings deep industry knowledge as well as a passion for open source! 

Steering Committee members, please indicate you vote via a +1 for yes or a -1 for no or 0 for abstaining.

**Comment by pstout** [comment]
+1

**Comment by duftler** [comment]
+1

**Comment by aglover** [comment]
+1

**Comment by demobox** [comment]
+1
