### ISSUE TITLE
REQUEST: Nomination of Andy Glover for Another Term on the Steering Committee

### ISSUE THREAD

**Issue by pstout** [spinnaker/governance#87]
I nominate Andy Glover for another term on the Steering Committee.  Andy's current term ends on 12/31/2019.

Andy Glover is the Director of Delivery Engineering at Netflix. He and his team own and operate Spinnaker at Netflix.

Steering Committee members, please indicate you vote via a +1 for yes or a -1 for no or 0 for abstaining.  As per the Spinnaker project’s rules, Andy does not have a vote on his election.

**Comment by pstout** [comment]
+1

**Comment by demobox** [comment]
+1

**Comment by duftler** [comment]
+1
