### ISSUE TITLE
REQUEST: Nomination of Matt Duftler for Another Term on the Steering Committee

### ISSUE THREAD

**Issue by pstout** [spinnaker/governance#91]
I nominate Matt Duftler for another term on the Steering Committee. Matt's previous term ended on 12/31/2019.

Matt is a Staff Software Engineer on the Cloud Continuous Delivery team at Google in NYC.  Matt has been working on the Spinnaker project since Google became involved in 2014, and was a co-creator of several of its services.

Steering Committee members, please indicate you vote via a +1 for yes or a -1 for no or 0 for abstaining. As per the Spinnaker project’s rules, Matt does not have a vote on his election.

**Comment by pstout** [comment]
This nomination was first presented at the beginning of the Steering Committee meeting on Friday, January 10th.  Three of the other members of the Steering Committee (Andrew Phillips, Erin Kidwell, and Peter Stout) were present and voted in favor of his reelection during the call so that Matt could participate in the meeting as a member of the committee.  This issue is being opened to capture the voting (and give Andy Glover an opportunity to vote).

**Comment by pstout** [comment]
+1

**Comment by demobox** [comment]
+1

**Comment by aglover** [comment]
+1!

**Comment by aglover** [comment]
@emkidwell FYI

**Comment by emkidwell** [comment]
+1 in case this is still necessary

**Comment by plumpy** [comment]
I don't know why @duftler refuses to vote for himself, but I'm going to go ahead and close this since every else voted in favor.
